### PR TITLE
Version 1.3.2

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by rodinux** [comment]
Hello @ericgaspar, can we begin adapt this code with some staff from cleaning, but without the email because it haven't be fixed yet...

**Comment by ericgaspar** [comment]
I would rather prefer that a branch is created for mail so we can merge `cleaning` branch to testing

**Comment by rodinux** [comment]
> I would rather prefer that a branch is created for mail so we can merge `cleaning` branch to testing

Hello, yes, I have created a branch for test the problems with mails from cleaning here https://github.com/YunoHost-Apps/paheko_ynh/tree/fix-mail

If we want merge from cleaning, we have to change first some things... Can I suggest you on the PR cleaning what we can keep and what we can't ?

**Comment by ericgaspar** [comment]
> If we want merge from cleaning, we have to change first some things... Can I suggest you on the PR cleaning what we can keep and what we can't ?
Sure, just creat a branch with your changes

**Comment by rodinux** [comment]
You can't use `mupdf` for pdf files, I think is better not try add packages for pdf, there is a native extension DomPdf in the app which did'nt need add others packages !

**Comment by rodinux** [comment]
> You can't use `mupdf` for pdf files, I think is better not try add packages for pdf, there is a native extension DomPdf in the app which did'nt need add others packages, I think we can

**Comment by rodinux** [comment]
!testme

**Pull request closed without merging**
