### PR TITLE
Update to 1.2.7

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
!testme

**Comment by fflorent** [comment]
LGTM

**Comment by rodinux** [comment]
> LGTM

Hello, can you also review ?

**Comment by fflorent** [comment]
LGTM means Looks Good To Me, means that I am OK with the merge

**Comment by rodinux** [comment]
Ok, so I ` Merge without waiting for requirements to be met (bypass branch protections) ` ?

**Review by fflorent — APPROVED** [review]

**Comment by fflorent** [comment]
Is this what makes you more comfortable?

**Comment by rodinux** [comment]
> Is this formal approval what makes you more comfortable?

sorry, I thought it was better, but anyway it's the same...

**Pull request merged**
