### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *First try to prepare transition between garradin_ynh to paheko_ynh*

## Solution

- *try add the scripts looking the example of how the transition was been done between gogs to gitea*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
testme!

**Review by ericgaspar — APPROVED** [review]

**Comment by fflorent** [comment]
I see the start of the `if`` block, but where does it end? (shouldn't it end with a `fi` normally?)

https://github.com/YunoHost-Apps/paheko_ynh/blob/9fc164edba893734057893870884f31216c285f5/scripts/upgrade#L78

**Comment by fflorent** [comment]
Neither Garradin nor Paheko have any data directory, do they? So I guess the `$datadir` must not be set:
https://github.com/YunoHost-Apps/paheko_ynh/blob/9fc164edba893734057893870884f31216c285f5/scripts/upgrade#L86

**Comment by fflorent** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
